name: Exo ARC

on:
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: exo-arc-runner
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.test
                  tags: ghcr.io/${{ github.repository }}:latest
                  push: true
